.\"     Title: ddclient
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 08/08/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "DDCLIENT" "8" "08/08/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ddclient \- Update IP addresses at dynamic DNS services
.SH "SYNOPSIS"
.HP 9
\fBddclient\fR {\-help}
.HP 9
\fBddclient\fR [\-daemon\ \fIinterval\fR] [\-proxy\ \fIhost\fR] [\-server\ \fIhost\fR] [\-protocol\ \fItype\fR] [\-file\ \fIconfigfile\fR] [\-cache\ \fIcachefile\fR] [\-pid\ \fIpidfile\fR] [\-use\ \fImechanism\fR] {\-if\ \fIinterface\fR | \-ip\ \fIipaddress\fR | \-web\ {\fIprovider\fR\ |\ \fIurl\fR} | \-fw\ \fIfirewall\fR | \-cmd\ \fIcommand\fR}
.SH "DESCRIPTION"
.PP
ddclient is a little program to update IP addresses managed using dynamic DNS providers such as DynDNS.com.
.PP
For usage information please run
\fBddclient \-help\fR
until this manpage is finished.
